from setuptools import setup, find_packages

install_requires = [
    "gdown",
    "pyvirtualdisplay",
    "torch>=2.3.1",
    "torchvision>=0.18.1",
    "pytorch-lightning>=2.1.0",
    "numpy>=1.24.4,<2.0.0",
    "opencv-python>=4.8.1",
    "scipy>=1.10.1",
    "pyrender>=0.1.45",
    "trimesh>=3.9.0",
    "PyOpenGL>=3.1.0",
    "PyOpenGL_accelerate>=3.1.0",
    "scikit-image>=0.21.0",
    "smplx==0.1.28",
    "yacs",
    "timm",
    "einops",
    "xtcocotools",
    "pandas",
    "mediapipe",
    "supervision",
    "ultralytics",
    "hydra-core",
    "hydra-submitit-launcher",
    "hydra-colorlog",
    "pyrootutils",
    "rich",
    "webdataset",
    "dill",
    "pandas",
    "pafy",
    "youtube-dl",
    "pillow>=7.1.0",
    "easydict",
    "cython",
    "cffi",
    "msgpack",
    "pyyaml",
    "tensorboardX",
    "tqdm",
    "jinja2",
    "scikit-learn",
    "prettytable",
    "torchfile",
    "plyfile",
    "munkres",
    "shyaml",
    "numpy-quaternion",
    "pygame",
    "keyboard",
    "transforms3d",
    "bvhtoolbox",
    "vedo",
    "imgaug",
    "tensorboard",
    "plotly",
    "open3d",
    "addict",
    "loguru",
    "norfair",
    "h5py",
    "imageio-ffmpeg",
    "joblib",
    "chumpy@git+https://github.com/ojh6404/chumpy.git@patch-python3.11",
    "detectron2 @ git+https://github.com/facebookresearch/detectron2.git",
]


setup(
    name="motion_capture",
    packages=find_packages(),
    install_requires=install_requires,
    eager_resources=["*"],
    include_package_data=True,
    python_requires=">=3.8",
    description="Motion Capture Utils for Human Pose Estimation and Hand Pose Estimation with 3D Mesh Reconstruction",
    author="Jihoon Oh",
    url="https://github.com/ojh6404/motion_capture",
    author_email="ojh6404@gmail.com",
    version="0.0.2",
)
